version: '3'

# Usage: docker-compose -f ./docker-compose.yml up
services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    restart: always
    environment:
      SOME_ENV: value
    ports:
      - '5672:5672'
      - '15672:15672'
#    volumes:
#      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
#    networks:
#      - rabbitmq_net

#networks:
#  rabbitmq_net:
#    driver: bridge