apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: function-app-web
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: dev.local/function-app-web:0.0.2-SNAPSHOT
        imagePullPolicy: Never
        env:
        - name: TARGET
          value: "Spring Boot Sample v1"
  traffic:
      - latestRevision: true
        percent: 50
      - latestRevision: false
        percent: 50
        revisionName: function-app-web-00002